import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ThemeToggle from "../components/ThemeToggle";
import Sidebar from "../components/Sidebar";
import "./globals.css";
import { DocProvider } from "../context/DocContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}>
        {/* Theme Toggle Button */}
        <ThemeToggle />
        <DocProvider>
          <div className="flex min-h-screen">
            {/* Sidebar Navigation */}
            <div className="hidden md:block">
              {/* Sidebar component */}
              <div className="h-full">
                <Sidebar />
              </div>
            </div>
            {/* Main Content */}
            <main className="flex-1 p-6 md:p-12">{children}</main>
          </div>
        </DocProvider>
      </body>
    </html>
  );
}
